/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ti_chromium_browser_cef_N_CefBrowser */

#ifndef _Included_com_ti_chromium_browser_cef_N_CefBrowser
#define _Included_com_ti_chromium_browser_cef_N_CefBrowser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_CreateBrowser
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1CreateBrowser
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1Destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_SetWindowSize
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1SetWindowSize
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_SetUrl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1SetUrl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_GetUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1GetUrl
  (JNIEnv *, jobject);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_IsBackEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1IsBackEnabled
  (JNIEnv *, jobject);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_Back
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1Back
  (JNIEnv *, jobject);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_IsForwardEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1IsForwardEnabled
  (JNIEnv *, jobject);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_Forward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1Forward
  (JNIEnv *, jobject);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_Refresh
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1Refresh
  (JNIEnv *, jobject);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_Stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1Stop
  (JNIEnv *, jobject);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_Execute
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1Execute
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_Evaluate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1Evaluate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_CreateBrowserFunction
 * Signature: (Ljava/lang/String;Lcom/ti/chromium/browser/cef/CefBrowserFunction;)V
 */
JNIEXPORT void JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1CreateBrowserFunction
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_DestroyBrowserFunction
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1DestroyBrowserFunction
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_AddContextMenu
 * Signature: (ILjava/lang/String;Lcom/ti/chromium/browser/cef/CefBrowserContextMenu;)V
 */
JNIEXPORT void JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1AddContextMenu
  (JNIEnv *, jobject, jint, jstring, jobject);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_RemoveContextMenu
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1RemoveContextMenu
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_GetZoomLevel
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1GetZoomLevel
  (JNIEnv *, jobject);

/*
 * Class:     com_ti_chromium_browser_cef_N_CefBrowser
 * Method:    N_SetZoomLevel
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_ti_chromium_browser_cef_N_1CefBrowser_N_1SetZoomLevel
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
