/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ti_chromium_browser_cef_N_Cef */

#ifndef _Included_com_ti_chromium_browser_cef_N_Cef
#define _Included_com_ti_chromium_browser_cef_N_Cef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ti_chromium_browser_cef_N_Cef
 * Method:    N_EnableLogging
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ti_chromium_browser_cef_N_1Cef_N_1EnableLogging
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_ti_chromium_browser_cef_N_Cef
 * Method:    N_Initialize
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ti_chromium_browser_cef_N_1Cef_N_1Initialize
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_ti_chromium_browser_cef_N_Cef
 * Method:    N_Shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ti_chromium_browser_cef_N_1Cef_N_1Shutdown
  (JNIEnv *, jobject);

/*
 * Class:     com_ti_chromium_browser_cef_N_Cef
 * Method:    N_DoMessageLoopWork
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ti_chromium_browser_cef_N_1Cef_N_1DoMessageLoopWork
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
